name: Telegram_Notification

on: [create, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: TelegramBridge
        uses: GokulDas027/TelegramBridge@v1.0.b
        with:
          # Chat to send: chat id or @channel_name/add to secrets
          chat: ${{secrets.chat}}
          # Telegram Bot token/add to secrets
          token: ${{secrets.token}}
          # Job status
          status: ${{ job.status }}
          # Event triggered action
          event: ${{ github.event_name }}
          # Actor who did the action
          actor: ${{ github.actor }}
