name: Telegram_Notification

on: [create, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: notification
        if: cancelled() == false
        uses: xinthink/action-telegram@v1.1
        with:
          botToken: ${{ secrets.token }}
          chatId: ${{ secrets.chat }}
          jobStatus: ${{ job.status }}
